#!/bin/sh
########################################
# BLENDER PREP SCRIPT
########################################
date
export PS4=' $SECONDS + '
set -x

########################################
# SET THE WORKING DIRECTORY
########################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
export pid=${pid:-${jobid:?}}
#mkdir -p $DATA
#cd $DATA
#export TMPDIR=$DATA

####################################
# Specify NET Name and RUN
#
# RUN - RUN grib field to repack
####################################
export NET=${NET:-blend}
export RUN=${RUN:-blend}
export pgmout="OUTPUT.$$"

####################################
# Specify NBM version number
####################################
export BLEND_MODEL_VERSION=${BLEND_MODEL_VERSION:-${blend_ver}}

########################################
# SET THE EXECUTION VARIABLES           
########################################
export SCRIPTSblend=${SCRIPTSblend:-${HOMEblend}/scripts}
export FIXblend=${FIXblend:-${HOMEblend}/fix}
export PARMblend=${PARMblend:-${HOMEblend}/parm}
export EXECblend=${EXECblend:-${HOMEblend}/exec}
export UTILblend=${UTILblend:-${HOMEblend}/ush/util}
export USHblend=${USHblend:-${HOMEblend}/ush}
#export ARCHIVEblend=${ARCHIVEblend:-${$ARCHIVEblend}/archive_blend}
########################################
# SET THE DATE VARIABLES           
########################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh 12 1
. ./PDY

########################################
# SET THE INPUT DIRECTORIES             
########################################
#export COMINblendbase=${COMINblendbase:-$(compath.py -o ${NET}/${blend_ver})}
#export COMIN=${COMIN:-${COMINblendbase:?}}/blend.${PDY}/$cyc/modeldata

########################################
# SET THE OUTPUT DIRECTORIES             
########################################
#export COMOUTblendbase=${COMOUTblendbase:-$(compath.py -o ${NET}/${blend_ver})}
export COMOUT=${COMOUT:-${COMOUTblendbase:?}}/blend.$PDY/$cyc/modeldata
mkdir -m 755 -p $COMOUT

LEAD_TIME=${PBS_ARRAY_INDEX}

echo "******** RUNNING FOR $LEAD_TIME *************"

python $USHblend/qpf24_downscale_ai_pytorch.py $LEAD_TIME

export err=$?; err_chk

postmsg $jlogfile "$0 completed normally"

########################################
# CLEAN UP THE WORKING DIRECTORY         
########################################

if [ "$KEEPDATA" != "YES" ]; then
   rm -rf $DATA
fi

date
